name: Node.js 

on: 
 push:
  branches:
      - main
 workflow_dispatch: {}
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm install
      - run: npm test
  
