name: continues running jobs
on:
 workflow_dispatch: {}
jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: true
    steps:
          - name: running continues
            run: npm install
            
   
  test1:
    runs-on: ubuntu-latest
    needs: test
    steps:
          - name: running continues
            run: npm install
