name: continues running jobs
on:
 workflow_dispatch: {}
jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      fail-fast: true
    steps:
          - name: running continues
            run: npm -version
            
   
  test1:
    runs-on: ubuntu-latest
    needs: test
    steps:
          - name: running continues
            run: echo " test true only this test1 will   be execute"
