name: continues running jobs
on:
 workflows_dispatch: {}
 jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        version: [6, 7, 8 ]
        experimental: [false]
        include:
         - version: 9
           experimental: true
